services:
  # 后端服务
  backend:
    build: .
    container_name: video-parser-backend-test
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped

  # 前端服务（使用开发模式）
  frontend-dev:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: video-parser-frontend-test
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped 