services:
  # 后端服务（使用Chromium）
  backend:
    build: 
      context: .
      dockerfile: Dockerfile.simple
    container_name: video-parser-backend-chromium
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
      - CHROME_BIN=/usr/bin/chromium
      - CHROMEDRIVER_PATH=/usr/bin/chromedriver
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped

  # 前端服务
  frontend:
    build: ./frontend
    container_name: video-parser-frontend-chromium
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped 