version: '3.8'

services:
  # 后端服务
  backend:
    build: .
    container_name: video-parser-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    volumes:
      - ./instance:/app/instance
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - video-parser-network

  # 前端服务
  frontend:
    build: ./frontend
    container_name: video-parser-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - video-parser-network

  # Nginx反向代理（可选）
  nginx:
    image: nginx:alpine
    container_name: video-parser-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
    networks:
      - video-parser-network

  # Redis缓存（可选）
  redis:
    image: redis:alpine
    container_name: video-parser-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - video-parser-network

  # 监控服务（可选）
  monitoring:
    image: prom/prometheus:latest
    container_name: video-parser-monitoring
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped
    networks:
      - video-parser-network

volumes:
  redis_data:

networks:
  video-parser-network:
    driver: bridge 